apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: instaslice-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: instaslice-operator
  name: instaslice-operator-webhook-service
  namespace: instaslice-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
